project:
  type: website
  output-dir: docs

website:
  title: "SPS 509 | Advanced Quantitative Methods"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - icon: slack
        href: "https://sps509.slack.com"
        aria-label: Slack
      - icon: cloud-fill
        href: "https://posit.cloud"
        aria-label: posit.cloud


format:
  html:
   template-partials:
    - html/home/title-block.html
   theme:
    light: flatly
    dark: darkly



