---
title: "SPS 502 Final Project"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
date: "Due 2022-12-15, 11:59 P.M."
---

For your final project, you will take a dataset from the wild, explore it, wrangle and clean it, tell a story with it, and make inferences about it using regression analysis and other statistical tools.

# Data

I want this project to be as useful for you and your career as possible. Accordingly, you have a lot of freedom in what data you can use for this project. Choose a dataset from this list:

## Your own data

Use a dataset from your place of employment, previous data you have worked with, or data you have collected yourself. 

## Data from the internet

Go to [Google Dataset Search](https://toolbox.google.com/datasetsearch) (or anywhere else online), find an interesting dataset and ask questions about it. Here are some different high-quality datasets:

### Nonprofit management

- [U.S. Charities and Non-profits](https://www.kaggle.com/crawford/us-charities-and-nonprofits): All of the charities and nonprofits registered with the IRS^[Source: IRS. This is actually split into six separate files. You can combine them all into one massive national database with `bind_rows()`, or filter the data to include specific states (or a single state). It all depends on the story you're telling.] 
- [Nonprofit Grants 2010 to 2016](https://data.world/causebot/grant-2010-to-2016): Nonprofit grants made in the US as listed in Schedule I of the IRS 990 tax form between 2010 to 2016^[Source: IRS]

### Federal, state, and local government management
- [Transparent Idaho](https://transparent.idaho.gov/): Financial and personnel data for Idaho state government
- [Deadly traffic accidents in the UK (2015)](https://www.kaggle.com/kwullum/deadly-traffic-accidents-in-the-uk-2015): List of all traffic-related deaths in the UK in 2015^[Source: [data.gov.uk](https://data.gov.uk/dataset/road-accidents-safety-data/resource/ceb00cff-443d-4d43-b17a-ee13437e9564)]
- [Firefighter Fatalities in the United States](https://www.kaggle.com/fema/firefighter-fatalities): Name, rank, and cause of death for all firefighters killed since 2000^[Source: FEMA]
- [Federal Emergencies and Disasters, 1953–Present](https://www.kaggle.com/fema/federal-disasters): Every federal emergency or disaster declared by the President of the United States since 1953^[Source: FEMA]
- [Global Terrorism Database (1970–2016)](https://www.kaggle.com/START-UMD/gtd): 170,000 terrorist attacks worldwide, 1970-2016^[Source: National Consortium for the Study of Terrorism and Responses to Terrorism (START), University of Maryland]
- [City of Austin 311 Unified Data](https://data.world/cityofaustin/i26j-ai4z): All 311 calls to the City of Austin since 2014^[Source: City of Austin]

### Higher education

- [Integreated Postsecondary Education Data System (IPEDS)](https://nces.ed.gov/ipeds/): IPEDS gathers information from every college, university, and technical and vocational institution that participates in the federal student financial aid programs. The Higher Education Act of 1965, as amended, requires that institutions that participate in federal student aid programs report data on enrollments, program completions, graduation rates, faculty and staff, finances, institutional prices, and student financial aid.

- [National Longitudinal Survey of Freshmen (NLSF)](https://nlsf.princeton.edu): The National Longitudinal Survey of Freshmen (NLSF) followed a cohort of first-time freshman at selective colleges and universities through their college careers. Equal numbers of whites, blacks, Hispanics, and Asians were sampled at each of the 28 participating schools. Among other uses, the data has been collected with the testing of several competing theories of minority under performance in college in mind.

### Polisci

- [Comparative Political Dataset](http://www.cpds-data.org): The "Comparative Political Data Set" (CPDS) is a collection of political and institutional country-level data provided by Prof. Dr. Klaus Armingeon and collaborators at the University of Berne. It consists of annual data for 36 democratic countries for the period of 1960 to 2017 or since their transition to democracy.

- [Correlates of State Policy](http://ippsr.msu.edu/public-policy/correlates-state-policy): The Correlates of State Policy Project aims to compile, disseminate, and encourage the use of data relevant to U.S. state policy research, tracking policy differences across and change over time in the 50 states. 

- [fivethirtyeight](https://www.rdocumentation.org/packages/fivethirtyeight/versions/0.5.0): Datasets and code published by the data journalism website 'FiveThirtyEight' available at <https://github.com/fivethirtyeight/data>.



# Final report

You will turn in a report where you define your research questions, explore and describe your data, build models and make inferences, discuss the implications of those findings, and make recommendations. 

## Requirements

In your final paper, you need to include at least one of **each** of the following elements (i.e. at least one plot, but more is fine; at least one regression model, but more is fine):

- A plot of a single variable (like a histogram; see ModernDive 2)
- A plot of multiple variables (like a scatterplot; see ModernDive 2)
- 2-3 hypotheses that you will test 
- A multiple regression model (see ModernDive 5, 6, and 10)

## Outline

Here is a suggested outline for your final report:

1. **Executive summary**: one-page summary of your questions, methods, findings, and recommendations
2. **Introduction and description of research questions**: describe the motivation for this study, outline and define what questions you are exploring and why
3. **Data and methods**: explain how the data was collected, provide basic summary statistics (tables and figures) of the main variables you're interested in, and describe what statistical tools you will use to answer your questions (i.e. regression, bootstrapped comparisons of means, etc.)
4. **Results**: answer each of your questions using statistical tools and interpret the results of the different statistical tests you use
5. **Limitations of the study**: provide caveats for your analysis and explain how confident you are in your results
6. **Recommendations and conclusion**: discuss the implications of these findings and make recommendations based on the results
7. **Appendices**: if you want to include tables of summary statistics or tables showing alternative models, you can include them in an appendix instead of in the body of the report itself.


# Instructions

Here's what you'll need to do:

1. Choose a dataset.
2. Look at the different columns it has available and think of 2-3 questions you want to answer with it.^[If you want, you can combine multiple datasets too] 
3. Identify your main outcome (y) variable (or multiple if you want). Identify which variables explain variation in the outcome (x, or explanatory variables).
4. Explore the data, either inside R Markdown chunks in the final report itself, or in a separate R Markdown file called `exploratory.Rmd` (or whatever you want to call it)—that way you're not running all your intermediate plots and models and tests in the final document.
5. Answer your questions with the data and interpret the results.
6. Put the text of your final report and interpretation and analysis, etc. in the R Markdown file for the final report. **Note:** You don't have to type the actual text inside RStudio (which doesn't have an automatic spell checker). You can use a Google Doc or a Word file or something similar, write the text of your report there, and then copy/paste the text into your final R Markdown file.
7. Knit the report as a Word file or PDF.
10. Submit the following items on Canvas:
    - Knitted Word file or PDF with no code included
    - Knitted Word file or PDF *with* code included

